### ISSUE TITLE
Example on WSJ.com doesn't work for unautheticated users

### ISSUE THREAD

**Issue by yaph** [dowjones/pinpoint#2]
To access the example you have to be logged in and/or a WSJ subscriber. I guess this draws more people away from this project than becoming a WSJ subscriber.

**Comment by ejb** [comment]
Thanks for bringing this to my attention. I've replaced the link with a different (free to access) article.

**Comment by yaph** [comment]
Thanks for your effort, but the new page is still not accessible.

**Comment by ejb** [comment]
Oh drat. I've changed it again - does this work outside the paywall? http://www.wsj.com/articles/when-napoleon-met-his-waterloo-he-was-out-of-town-1433894903

**Comment by yaph** [comment]
Yes, this page works, thanks!

Are all WSJ articles "paywalled" after a certain time though?

**Comment by ejb** [comment]
I don't think so. If it becomes paywalled in the future, I will replace it with another link.

Now that it's out, I also hope to add a few examples on jsfiddle.

Thanks again for your help!

**Comment by yaph** [comment]
No problem, thanks for this tool!
